const appConfig = () => ({
  environment: process.env.NODE_ENV || 'development',
  jwt_secret: process.env.JWT_SECRET,
  cookie_secret: process.env.COOKIE_SECRET,
  access_token_expiration_minute: process.env.JWT_ACCESS_EXPIRATION_MINUTES,
  refresh_token_expiration_days: process.env.JWT_REFRESH_EXPIRATION_DAYS,
  master_password: process.env.MASTER_PASSWORD,
  mongodb_url: process.env.MONGODB_URL,
  smtp_host: process.env.SMTP_HOST,
  smtp_port: process.env.SMTP_PORT,
  smtp_invoice_email: process.env.SMTP_INVOICE_EMAIL,
  smtp_invoice_password: process.env.SMTP_INVOICE_PASSWORD,
  smtp_invoice_sender_email: process.env.SMTP_INVOICE_SENDER_EMAIL,
  smtp_support_email: process.env.SMTP_SUPPORT_EMAIL,
  smtp_support_password: process.env.SMTP_SUPPORT_PASSWORD,
  smtp_info_email: process.env.SMTP_INFO_EMAIL,
  smtp_info_password: process.env.SMTP_INFO_PASSWORD,
  smtp_auth_email: process.env.SMTP_AUTH_EMAIL,
  smtp_auth_password: process.env.SMTP_AUTH_PASSWORD,
  paypal_client_id: process.env.PAYPAL_CLIENT_ID,
  paypal_client_secret: process.env.PAYPAL_CLIENT_SECRET,
  alien_tech_client_id: process.env.ALIEN_TECH_CLIENT_ID,
  alien_tech_secret_key: process.env.ALIEN_TECH_SECRET_KEY,
  aws_access_key_id: process.env.AWS_ACCESS_KEY_ID,
  aws_secret_access_key: process.env.AWS_SECRET_ACCESS_KEY,
  evc_api_id: process.env.EVC_API_ID,
  evc_username: process.env.EVC_USERNAME,
  evc_password: process.env.EVC_PASSWORD,
  catapush_app_id: process.env.CATAPUSH_APP_ID,
  catapush_messenger_id: process.env.CATAPUSH_MESSENGER_ID,
  catapush_app_key: process.env.CATAPUSH_APP_KEY,
  permanent_token: process.env.PERMANENT_TOKEN,
  catapush_client_id: process.env.CATAPUSH_CLIENT_ID,
  catapush_client_secret: process.env.CATAPUSH_CLIENT_SECRET,
  auto_tuner_api_key: process.env.AUTO_TUNER_API_KEY,
  auto_tuner_id: process.env.AUTO_TUNER_ID,
  auto_flasher_api_key: process.env.AUTO_FLASHER_API_KEY,
  sftp_host: process.env.SFTP_HOST,
  sftp_port: process.env.SFTP_PORT,
  sftp_user: process.env.SFTP_USER,
  sftp_password: process.env.SFTP_PASSWORD,
  redis_host: process.env.REDIS_HOST,
  redis_port: process.env.REDIS_PORT,
  evc_base_url: process.env.EVC_BASE_URL,
  encryption_key: process.env.ENCRYPTION_KEY,
  mega_email: process.env.MEGA_EMAIL,
  mega_password: process.env.MEGA_PASSWORD,
});

type AppConfig = ReturnType<typeof appConfig>;

export { appConfig, AppConfig };
