export const collectionsName = {
    user: 'user',
    admin: 'admin',
    employee: 'employee',
    customer: 'customer',
    customerType: 'customer-type',
    car: 'car',
    controller: 'controller',
    setting: 'setting',
    credential: 'credential',
    schedule: 'schedule',
    verificationMail: 'verification-mail',
    notice: 'notice',
    invoice: 'invoice',
    supportTicket: 'support-ticket',
    solution: 'solution',
    solutionInformation: 'solution-information',
    script: 'script',
    fileService: 'file-service',
    tempFileService: 'temp-file-service',
    pricing: 'pricing',
    creditPricing: 'credit-pricing',
    chat: 'chat',
    employeeRole: 'employee-role',
    permission: 'permission',
    adminPricing: 'admin-pricing',
    dtc: 'dtc',
};
