export const collectionsName = {
  user: 'User',
  admin: 'Admin',
  employee: 'Employee',
  customer: 'Customer',
  customerType: 'CustomerType',
  car: 'Car',
  controller: 'Controller',
  setting: 'Setting',
  credential: 'Credential',
  schedule: 'Schedule',
  verificationMail: 'verificationMail',
  notice: 'Notice',
  invoice: 'Invoice',
  supportTicket: 'SupportTicket',
  solution: 'Solution',
  solutionInformation: 'SolutionInformation',
  script: 'Script',
  fileService: 'FileService',
  pricing: 'Pricing',
};
