export const collectionsName = {
  user: 'user',
  admin: 'admin',
  employee: 'employee',
  customer: 'customer',
  customerType: 'customer-type',
  car: 'car',
  controller: 'controller',
  setting: 'setting',
  credential: 'credential',
  schedule: 'schedule',
  verificationMail: 'verification-mail',
  notice: 'notice',
  invoice: 'invoice',
  supportTicket: 'supportTicket',
  solution: 'solution',
  solutionInformation: 'solution-information',
  script: 'script',
  fileService: 'fileService',
  tempFileService: 'tempFileService',
  pricing: 'pricing',
  creditPricing: 'creditPricing',
  chat: 'chat',
};
